sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 550002
  #redis配置
  redis:
    host: localhost
    port: 6379
    password: 550002
    database: 10
  alioss:
    bucket-name: ymyaccbucket
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKWM2co3x52uFtRvsZy
    access-key-secret: PvXajAMuJvQAYsNsBaySk5Qq6ZkH8G
#mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: 550002
