server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  #redis配置
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}
#mysql配置
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 86400000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  #阿里云配置文件
  alioss:
    access-key-id: ${sky.alioss.access-key-id}
    endpoint: ${sky.alioss.endpoint}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}



#阿里云配置文件
aliyun:
  oss:
    file:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      KeyId: LTAI5tKWM2co3x52uFtRvsZy
      KeySecret: PvXajAMuJvQAYsNsBaySk5Qq6ZkH8G
      bucketName: ymyaccbucket